{% set version = "1.0.7" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyquant
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyquant_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyquant/tidyquant_{{ version }}.tar.gz
  sha256: 90641de67eabf1b84b3ea2fdcd282977121a099ec906a894096ea225ba6967dd

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-alphavantager >=0.1.2
    - r-cli
    - r-curl
    - r-dplyr >=1.0.0
    - r-ggplot2
    - r-httr
    - r-jsonlite
    - r-lazyeval
    - r-lubridate
    - r-magrittr
    - r-performanceanalytics
    - r-purrr
    - r-quandl
    - r-quantmod >=0.4_13
    - r-readr
    - r-readxl
    - r-riingo
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr >=1.0.0
    - r-tidyselect
    - r-tidyverse
    - r-timedate
    - r-timetk >=2.4.0
    - r-ttr
    - r-xts
  run:
    - r-base
    - r-alphavantager >=0.1.2
    - r-cli
    - r-curl
    - r-dplyr >=1.0.0
    - r-ggplot2
    - r-httr
    - r-jsonlite
    - r-lazyeval
    - r-lubridate
    - r-magrittr
    - r-performanceanalytics
    - r-purrr
    - r-quandl
    - r-quantmod >=0.4_13
    - r-readr
    - r-readxl
    - r-riingo
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr >=1.0.0
    - r-tidyselect
    - r-tidyverse
    - r-timedate
    - r-timetk >=2.4.0
    - r-ttr
    - r-xts

test:
  commands:
    - $R -e "library('tidyquant')"           # [not win]
    - "\"%R%\" -e \"library('tidyquant')\""  # [win]

about:
  home: https://business-science.github.io/tidyquant/
  dev_url: https://github.com/business-science/tidyquant
  doc_url: https://business-science.github.io/tidyquant/reference/index.html
  license: MIT
  summary: Bringing business and financial analysis to the 'tidyverse'. The 'tidyquant' package provides a convenient wrapper to various 'xts', 'zoo', 'quantmod', 'TTR' and 'PerformanceAnalytics' package functions and returns the objects in the tidy 'tibble' format. The main advantage is being able to use quantitative functions
    with the 'tidyverse' functions including 'purrr', 'dplyr', 'tidyr', 'ggplot2', 'lubridate', etc. See the 'tidyquant' website for more information, documentation and examples.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - conda-forge/r
    - oblute
    - rluria14
    - benhuff
