{% set version = "1.0.11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tidyquant
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyquant_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyquant/tidyquant_{{ version }}.tar.gz
  sha256: af12e64d6e2ea99549ccafa161d578fd41689517cfe55c91ad8c776afcdfa72d

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-performanceanalytics
    - r-ttr
    - r-cli
    - r-curl
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.4.0
    - r-httr
    - r-httr2
    - r-lazyeval
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-quantmod >=0.4_13
    - r-readr
    - r-readxl
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr >=1.0.0
    - r-timedate
    - r-timetk >=2.4.0
    - r-xts
    - r-zoo
  run:
    - r-base
    - r-performanceanalytics
    - r-ttr
    - r-cli
    - r-curl
    - r-dplyr >=1.0.0
    - r-ggplot2 >=3.4.0
    - r-httr
    - r-httr2
    - r-lazyeval
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-quantmod >=0.4_13
    - r-readr
    - r-readxl
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr >=1.0.0
    - r-timedate
    - r-timetk >=2.4.0
    - r-xts
    - r-zoo

test:
  commands:
    - $R -e "library('tidyquant')"           # [not win]
    - "\"%R%\" -e \"library('tidyquant')\""  # [win]

about:
  home: https://business-science.github.io/tidyquant/
  dev_url: https://github.com/business-science/tidyquant
  doc_url: https://business-science.github.io/tidyquant/reference/index.html
  license: MIT
  summary: Bringing business and financial analysis to the 'tidyverse'. The 'tidyquant' package provides a convenient wrapper to various 'xts', 'zoo', 'quantmod', 'TTR' and 'PerformanceAnalytics' package functions and returns the objects in the tidy 'tibble' format. The main advantage is being able to use quantitative functions
    with the 'tidyverse' functions including 'purrr', 'dplyr', 'tidyr', 'ggplot2', 'lubridate', etc. See the 'tidyquant' website for more information, documentation and examples.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - mxr-conda
    - oblute
    - rluria14
    - benhuff
