bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: Nxsat5qPoniGVZdoIJGC6BZ6a4xtu/QRgWCEFqNSZa/lTDwbSukiVnZu2Cc3vBHzr9opd2mEt4EfLMTifHYHZbk0b4SwPE2BzF/qvkeOaCGChcJeuNgWxeiLYEbbzMIQc9cS8JOXUb1oxyE2XdgcLkzmKCT1EDj2rAFLj1y6sI+FLzKeakkM+KVbEwZiJ//1K4o83FWFuA19t0VEJhPre0uiy+zO0r2LqxFs216DGOfiRpmxSftcMkoqRZ/PMlbxHjIKZbneNh8RoBGhLIP9awGPRj2o5VFt3U9y5tsK3pmwjZARsmbqh63+c1+DbvfcFw9v5Ce/248GcSeAjBc5ZM/G8Mr+HV6uvVuN4/5V5jDurTTm9gNMwsWmErLisZEf3Apw3imIrEljlNGAk0QqMtkS7oiXlsiJEot9u29+CgkJIjbHb0XZb6qwCt0A7jxwjT2x4ntpTRjfPHpcfmKNNc77gZIoW5cVSG6L0ZJIbiYaiIfJixw97TMd1DIHK+RTGNtmEJdZmhnSkJz8++yYX8swxWg6N+jG10KTrqg5o7v2UVKRRh56xbRNAlI4XtXq8SKI+ZbDF9nN2MkNQ91TdQfdWeDkDJ4IB9/nuLAKkwjW4e7ghC5F/WVLc6KsENj2k1pOaaZx+mJauk3ytz0YS2md+j9IeVMRHdqGmgvLQ1c=
conda_forge_output_validation: true
